
package com.mycompany.valenbiciapiv2;

// Importamos las clases de conexion a mysql y los drivers de sql
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author diego
 */
public class ConexiónBDD extends javax.swing.JFrame {
// Declaramos la conexion a mysql
    private static Connection con;
    private static Statement s;
    protected static DatosJSon dJSon;
    private static int numEst = 3;

    private static final String driver = "com.mysql.cj.jdbc.Driver";//com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "administrador";
    private static final String url = "jdbc:mysql://localhost:3306/valenbicidb?";
    // Función que va a conectarse a mi BDD de mysql
    /**
 * Creates new form ConexionBDD
 * root@localhost:3306
 */
    
    public ConexiónBDD() {
        initComponents();
        dJSon = new DatosJSon(numEst);
        jTextFieldNumEst.setText(""+numEst);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonConectarBDD = new javax.swing.JButton();
        jButtonCerrarCxBDD = new javax.swing.JButton();
        jButtonAddBDD = new javax.swing.JButton();
        jButtonDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelDatosEstaciones = new javax.swing.JLabel();
        jLabelEstConexBDD = new javax.swing.JLabel();
        jLabelAddBDD = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNumEst = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonConectarBDD.setText("Conex. BDD");
        jButtonConectarBDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConectarBDDMouseClicked(evt);
            }
        });

        jButtonCerrarCxBDD.setText("Cerrar Conexión");
        jButtonCerrarCxBDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCerrarCxBDDMouseClicked(evt);
            }
        });
        jButtonCerrarCxBDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarCxBDDActionPerformed(evt);
            }
        });

        jButtonAddBDD.setText("Añadir a BDD");
        jButtonAddBDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddBDDMouseClicked(evt);
            }
        });
        jButtonAddBDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBDDActionPerformed(evt);
            }
        });

        jButtonDatos.setText("Datos");
        jButtonDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDatosMouseClicked(evt);
            }
        });
        jButtonDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatosActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de estaciones a consultar ---->");

        jLabelDatosEstaciones.setText("Obtener Datos de Estaciones");

        jLabelEstConexBDD.setText("Estado Conexión");

        jLabelAddBDD.setText("Primero Obtener Datos y Conectar BDD ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("ValenbiciAPIv2");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(jTextFieldNumEst, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDatosEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConectarBDD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEstConexBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelAddBDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAddBDD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCerrarCxBDD)
                        .addGap(9, 9, 9))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabelAddBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddBDD)
                        .addComponent(jButtonCerrarCxBDD)
                        .addComponent(jButtonDatos)
                        .addComponent(jButtonConectarBDD)
                        .addComponent(jLabelDatosEstaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNumEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelEstConexBDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDatosActionPerformed

    private void jButtonAddBDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddBDDActionPerformed

    private void jButtonCerrarCxBDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarCxBDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCerrarCxBDDActionPerformed

    private void jButtonCerrarCxBDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarCxBDDMouseClicked
        // TODO add your handling code here:
        try {
         con.close();
         jLabelEstConexBDD.setText("Sin conexión");
        } catch (SQLException ex) {
            Logger.getLogger(ConexiónBDD.class.getName()).log(Level.SEVERE, null, ex);
 }
    }//GEN-LAST:event_jButtonCerrarCxBDDMouseClicked

    
    private void jButtonAddBDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddBDDMouseClicked
        // TODO add your handling code here:
      try{
            String[] query = dJSon.getValues();
            System.out.println("Añadiendo "+query.length+" estaciones." );
            
           for (int i = 0; i < query.length; i++) {
               
                String[] datos = query[i].split("<");
                String idEstacion = datos[0].trim();
                String direccion = datos[1].trim();
                String bicisDisp = datos[2].trim();
                String anclajesLib = datos[3].trim();
                String estado = datos[4].trim();
                    if (estado == "T"){estado = "1";}else{estado = "0";}
                String lat = datos[5].trim(); 
                String lon = datos[6].trim(); 

                s = con.createStatement();
                String sql = "INSERT INTO historico (estacion_id, direccion, bicis_disponibles, anclajes_libres, estado_operativo, fecha_registro, ubicación) " 
                            + "VALUES (" + idEstacion + ", '" + direccion.replace("'", "''") + "', " + bicisDisp + ", " 
                            + anclajesLib + ", '" + estado + "', CURRENT_TIMESTAMP, "
                            + "POINT(" + lat + ", " + lon + "))";
                System.out.println("SQL: " + sql); // Para depuración
                s.executeUpdate(sql);
                            
                 
                
            }
            s.close();
                        
           
      }
          // Si la conexion NO fue exitosa mostramos un mensaje de error
        catch (SQLException e) {
            System.out.println(e);
        jLabelAddBDD.setText("Error de conexion" + e);
        
     }

    }//GEN-LAST:event_jButtonAddBDDMouseClicked

    private void jButtonConectarBDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConectarBDDMouseClicked
        // TODO add your handling code here:
        System.out.println("Pulsado Boton Conexión");
        conector();
        jButtonAddBDD.setEnabled(true);
    }//GEN-LAST:event_jButtonConectarBDDMouseClicked

    private void jButtonDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDatosMouseClicked
        // TODO add your handling code here:
        numEst = Integer.parseInt(jTextFieldNumEst.getText());
        dJSon.mostrarDatos(numEst);
        jLabelDatosEstaciones.setText("Datos de estaciones:");
        jTextArea1.setText(dJSon.getDatos());
    }//GEN-LAST:event_jButtonDatosMouseClicked
    private void jTextFieldNumEstFocusLost(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        numEst = Integer.parseInt(jTextFieldNumEst.getText());
        dJSon.mostrarDatos(numEst);
        jLabelDatosEstaciones.setText("Datos estaciones:");
        jTextArea1.setText(dJSon.getDatos());
    } 
    // Declaramos los datos de conexion a la bd
    public void conector() {
        try {
            // Añade aquí el código para establecer la conexión con la base de datos
            Class.forName(driver);
            con = DriverManager.getConnection(url,user,pass); 
            System.out.println("Conexión Establecida");
            jLabelEstConexBDD.setText("Conexión establecida");

        }  catch (SQLException e) {
            System.out.println("SQL Exception: "+ e.toString());
            
        
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(ConexiónBDD.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexiónBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexiónBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexiónBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexiónBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexiónBDD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBDD;
    private javax.swing.JButton jButtonCerrarCxBDD;
    private javax.swing.JButton jButtonConectarBDD;
    private javax.swing.JButton jButtonDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAddBDD;
    private javax.swing.JLabel jLabelDatosEstaciones;
    private javax.swing.JLabel jLabelEstConexBDD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldNumEst;
    // End of variables declaration//GEN-END:variables
}
